#!/usr/bin/env bash
# Controlled RSLAQ validation campaign.
#
# Runs six comparable lines over the same scenarios/seeds/budget:
#   1) network-only ns-3 baselines, without DRL optimization;
#   2) DDQN with the paper-faithful RSLAQ reward;
#   3) DDQN with the resource-efficient reward contribution;
#   4) SAC with the paper-faithful RSLAQ reward;
#   5) SAC with the resource-efficient reward contribution;
#   6) Predictive SAC (forecaster + resource-efficient reward).
#
# The forecaster is trained from the baseline data generated by step 1,
# ensuring scenario/seed consistency across all lines.

set -Eeuo pipefail

REPO_ROOT="${REPO_ROOT:-/home/elioth/Documentos/artigo_jussi}"
NS3_DIR="${NS3_DIR:-${REPO_ROOT}/ns-3-dev}"
GYM_DIR="${GYM_DIR:-${REPO_ROOT}/ns-o-ran-gym}"

RUN_TAG="${RUN_TAG:-$(date +%Y%m%d_%H%M%S)}"
EXPERIMENT_LINE="${EXPERIMENT_LINE:-rslaq_sla_resource_efficiency}"
OUTPUT_ROOT="${OUTPUT_ROOT:-${GYM_DIR}/results_controlled/${EXPERIMENT_LINE}/${RUN_TAG}}"

SCENARIOS_INPUT="${SCENARIOS:-low_traffic normal congestion stressed insufficient_resources}"
SEEDS_INPUT="${SEEDS:-1 2 3 4 5}"
read -r -a SCENARIOS <<< "${SCENARIOS_INPUT}"
read -r -a SEEDS <<< "${SEEDS_INPUT}"

INTERACTION_STEPS="${INTERACTION_STEPS:-20000}"
EPISODE_STEPS="${EPISODE_STEPS:-100}"
EPISODES="$(python3 -c "import math; print(math.ceil(${INTERACTION_STEPS}/${EPISODE_STEPS}))")"

APP_START="${APP_START:-0.5}"
PERIOD_MS="${PERIOD_MS:-10}"
SIM_TIME="${SIM_TIME:-5.0}"
CONSECUTIVE_OUTAGE_STEPS="${CONSECUTIVE_OUTAGE_STEPS:-5}"
WARMUP_STEPS="${WARMUP_STEPS:-5}"
SEED_CYCLE="${SEED_CYCLE:-999999}"
DDQN_TERMINATE_ON_SLA_VIOLATION="${DDQN_TERMINATE_ON_SLA_VIOLATION:-0}"
SAC_TERMINATE_ON_SLA_VIOLATION="${SAC_TERMINATE_ON_SLA_VIOLATION:-0}"

P_STA_STATIC_FRACTION="${P_STA_STATIC_FRACTION:-0.5}"
RESOURCE_EFFICIENT_P_STA_STATIC_FRACTION="${RESOURCE_EFFICIENT_P_STA_STATIC_FRACTION:-0.25}"
P_STA_WEIGHTS="${P_STA_WEIGHTS:-0.3333,0.4000,0.2667}"
REWARD_ALPHA="${REWARD_ALPHA:-0.3333}"
REWARD_BETA="${REWARD_BETA:-0.4000}"
REWARD_GAMMA="${REWARD_GAMMA:-0.2667}"

DDQN_BUFFER_SIZE="${DDQN_BUFFER_SIZE:-10000}"
DDQN_BATCH_SIZE="${DDQN_BATCH_SIZE:-64}"
DDQN_LR="${DDQN_LR:-0.001}"
DDQN_GAMMA="${DDQN_GAMMA:-0.80}"
DDQN_EPS_START="${DDQN_EPS_START:-1.0}"
DDQN_EPS_MIN="${DDQN_EPS_MIN:-0.05}"
DDQN_EPS_DECAY="${DDQN_EPS_DECAY:-0.998}"
DDQN_TARGET_UPDATE="${DDQN_TARGET_UPDATE:-200}"

SAC_BUFFER_SIZE="${SAC_BUFFER_SIZE:-50000}"
SAC_BATCH_SIZE="${SAC_BATCH_SIZE:-256}"
SAC_LR="${SAC_LR:-0.001}"
SAC_GAMMA="${SAC_GAMMA:-0.99}"
SAC_TAU="${SAC_TAU:-0.005}"
SAC_ALPHA="${SAC_ALPHA:-0.1}"

RESOURCE_EFFICIENCY_WEIGHT="${RESOURCE_EFFICIENCY_WEIGHT:-0.25}"
NEED_MATCH_WEIGHT="${NEED_MATCH_WEIGHT:-0.30}"
WASTE_PENALTY_WEIGHT="${WASTE_PENALTY_WEIGHT:-0.35}"
UNDER_ALLOCATION_PENALTY_WEIGHT="${UNDER_ALLOCATION_PENALTY_WEIGHT:-0.15}"
EMBB_SOFT_GUARD_PENALTY_WEIGHT="${EMBB_SOFT_GUARD_PENALTY_WEIGHT:-0.25}"
EMBB_SOFT_GUARD_RATIO="${EMBB_SOFT_GUARD_RATIO:-0.80}"
ACTION_SMOOTHNESS_WEIGHT="${ACTION_SMOOTHNESS_WEIGHT:-0.05}"
RESOURCE_DYNAMIC_NEED_WEIGHT="${RESOURCE_DYNAMIC_NEED_WEIGHT:-0.75}"
RESOURCE_WASTE_DEADBAND="${RESOURCE_WASTE_DEADBAND:-0.03}"

COMPUTE_COST_PER_HOUR_USD="${COMPUTE_COST_PER_HOUR_USD:-0.0}"
COMPUTE_AVG_POWER_WATTS="${COMPUTE_AVG_POWER_WATTS:-0.0}"
COMPUTE_ELECTRICITY_COST_USD_PER_KWH="${COMPUTE_ELECTRICITY_COST_USD_PER_KWH:-0.0}"

PREDICTIVE_REWARD_MODE="${PREDICTIVE_REWARD_MODE:-resource_efficient}"
PREDICTIVE_P_STA_FRACTION="${PREDICTIVE_P_STA_FRACTION:-0.25}"
RISK_PENALTY="${RISK_PENALTY:-0.5}"
SOFT_PENALTY="${SOFT_PENALTY:-0.2}"
FORECAST_SEQUENCE_LEN="${FORECAST_SEQUENCE_LEN:-8}"
FORECAST_HORIZON="${FORECAST_HORIZON:-5}"
FORECASTER_EPOCHS="${FORECASTER_EPOCHS:-30}"
FORECASTER_BATCH_SIZE="${FORECASTER_BATCH_SIZE:-256}"
FORECASTER_LR="${FORECASTER_LR:-0.001}"
FORECASTER_HIDDEN_DIM="${FORECASTER_HIDDEN_DIM:-64}"
FORECASTER_LIMIT_FILES="${FORECASTER_LIMIT_FILES:-0}"
FORECASTER_CHECKPOINT="${FORECASTER_CHECKPOINT:-}"
PREDICTIVE_BASELINE_ROOT="${PREDICTIVE_BASELINE_ROOT:-${OUTPUT_ROOT}/baseline_ns3}"
PREDICTIVE_FORECAST_SOURCE_ROOT="${PREDICTIVE_FORECAST_SOURCE_ROOT:-${PREDICTIVE_BASELINE_ROOT}/results_rslaq_network_only}"
PREDICTIVE_FORECAST_SOURCE_FORMAT="${PREDICTIVE_FORECAST_SOURCE_FORMAT:-baseline}"

RUN_BASELINES="${RUN_BASELINES:-1}"
RUN_DDQN="${RUN_DDQN:-1}"
RUN_RESOURCE_EFFICIENT_DDQN="${RUN_RESOURCE_EFFICIENT_DDQN:-1}"
RUN_PAPER_SAC="${RUN_PAPER_SAC:-1}"
RUN_RESOURCE_EFFICIENT_SAC="${RUN_RESOURCE_EFFICIENT_SAC:-1}"
BASELINE_MODES="${BASELINE_MODES:-pure_rr pure_pf pure_bcqi}"
BUILD_NS3="${BUILD_NS3:-1}"
DRL_JOBS="${DRL_JOBS:-1}"
ENABLE_STEP_LOGGING="${ENABLE_STEP_LOGGING:-1}"
RUN_DRL_COMPARISON="${RUN_DRL_COMPARISON:-1}"
RUN_FORECASTER="${RUN_FORECASTER:-1}"
RUN_FORECASTER_GRU="${RUN_FORECASTER_GRU:-1}"
RUN_FORECASTER_LSTM="${RUN_FORECASTER_LSTM:-1}"
RUN_FORECASTER_COMPARISON="${RUN_FORECASTER_COMPARISON:-1}"
RUN_PREDICTIVE_SAC="${RUN_PREDICTIVE_SAC:-1}"
RUN_PREDICTIVE_SAC_GRU="${RUN_PREDICTIVE_SAC_GRU:-0}"
RUN_PREDICTIVE_SAC_LSTM="${RUN_PREDICTIVE_SAC_LSTM:-0}"

if ! [[ "${DRL_JOBS}" =~ ^[0-9]+$ ]] || (( DRL_JOBS < 1 )); then
    echo "DRL_JOBS must be a positive integer, got: ${DRL_JOBS}" >&2
    exit 1
fi

mkdir -p "${OUTPUT_ROOT}"

cat <<EOF
RSLAQ controlled validation
  line:              ${EXPERIMENT_LINE}
  output:            ${OUTPUT_ROOT}
  scenarios:         ${SCENARIOS[*]}
  seeds:             ${SEEDS[*]}
  budget:            ${EPISODES} episodes x ${EPISODE_STEPS} steps = $((EPISODES * EPISODE_STEPS))
  simTime:           ${SIM_TIME}s
  P_STA fraction:    paper=${P_STA_STATIC_FRACTION}, contribution=${RESOURCE_EFFICIENT_P_STA_STATIC_FRACTION}
  P_STA weights:     ${P_STA_WEIGHTS}
  reward weights:    ${REWARD_ALPHA},${REWARD_BETA},${REWARD_GAMMA}
  baselines:         ${RUN_BASELINES} (${BASELINE_MODES})
  DDQN RSLAQ:        ${RUN_DDQN}
  DDQNd contribution:${RUN_RESOURCE_EFFICIENT_DDQN}
  DDQN SLA terminal: ${DDQN_TERMINATE_ON_SLA_VIOLATION}
  SAC SLA terminal:  ${SAC_TERMINATE_ON_SLA_VIOLATION}
  SAC paper:         ${RUN_PAPER_SAC}
  SAC contribution:  ${RUN_RESOURCE_EFFICIENT_SAC}
  predictive SAC:    ${RUN_PREDICTIVE_SAC}
  predictive SAC GRU: ${RUN_PREDICTIVE_SAC_GRU}
  predictive SAC LSTM: ${RUN_PREDICTIVE_SAC_LSTM}
  forecaster:        ${RUN_FORECASTER}
  forecaster GRU:    ${RUN_FORECASTER_GRU}
  forecaster LSTM:   ${RUN_FORECASTER_LSTM}
  forecaster comparison: ${RUN_FORECASTER_COMPARISON}
  predictive baseline: ${PREDICTIVE_BASELINE_ROOT}
  forecast root:     ${PREDICTIVE_FORECAST_SOURCE_ROOT}
  forecast source:   ${PREDICTIVE_FORECAST_SOURCE_FORMAT}
  forecast:          seq=${FORECAST_SEQUENCE_LEN}, horizon=${FORECAST_HORIZON}, epochs=${FORECASTER_EPOCHS}
  predictive reward:  ${PREDICTIVE_REWARD_MODE}, P_STA=${PREDICTIVE_P_STA_FRACTION}
  risk/soft penalty:  ${RISK_PENALTY}/${SOFT_PENALTY}
  build ns-3:        ${BUILD_NS3}
  DRL jobs:          ${DRL_JOBS}
  step logging:      ${ENABLE_STEP_LOGGING}
  DRL comparison:    ${RUN_DRL_COMPARISON}
  contribution w:    eff=${RESOURCE_EFFICIENCY_WEIGHT}, match=${NEED_MATCH_WEIGHT}, waste=${WASTE_PENALTY_WEIGHT}, under=${UNDER_ALLOCATION_PENALTY_WEIGHT}, embb_guard=${EMBB_SOFT_GUARD_PENALTY_WEIGHT}, smooth=${ACTION_SMOOTHNESS_WEIGHT}
  compute cost:      hourly=${COMPUTE_COST_PER_HOUR_USD}, power=${COMPUTE_AVG_POWER_WATTS}W, electricity=${COMPUTE_ELECTRICITY_COST_USD_PER_KWH}/kWh
EOF

if [[ "${BUILD_NS3}" == "1" ]]; then
    cd "${NS3_DIR}"
    ./ns3 build rslaq-sim
else
    echo "[build] Skipping ns-3 build because BUILD_NS3=${BUILD_NS3}"
fi

if [[ "${RUN_BASELINES}" == "1" ]]; then
    echo "[baseline_ns3] Running pure ns-3 baseline matrix"
    SCENARIOS="${SCENARIOS[*]}" \
    SEEDS="${SEEDS[*]}" \
    RUNS="1" \
    BASELINE_MODES="${BASELINE_MODES}" \
    BUILD_NS3="0" \
    SIM_TIME="${SIM_TIME}" \
    APP_START="${APP_START}" \
    PERIOD_MS="${PERIOD_MS}" \
    OUTPUT_ROOT="${OUTPUT_ROOT}/baseline_ns3" \
    "${NS3_DIR}/run_all_scenarios.sh"
fi

cd "${GYM_DIR}"

run_ddqn() {
    local reward_mode="$1"
    local label="$2"
    local scenario="$3"
    local seed="$4"
    local p_sta_fraction="${P_STA_STATIC_FRACTION}"
    local terminal_args=()
    local step_logging_args=()
    if [[ "${reward_mode}" == "resource_efficient" ]]; then
        p_sta_fraction="${RESOURCE_EFFICIENT_P_STA_STATIC_FRACTION}"
    fi
    if [[ "${DDQN_TERMINATE_ON_SLA_VIOLATION}" == "1" ]]; then
        terminal_args+=(--terminate-on-sla-violation)
    fi
    if [[ "${ENABLE_STEP_LOGGING}" != "1" ]]; then
        step_logging_args+=(--no-step-logging)
    fi

    echo "[DDQN ${label}] scenario=${scenario} seed=${seed} reward=${reward_mode}"
    python3 examples/rslaq_train_ddqn.py \
        --scenario "${scenario}" \
        --episodes "${EPISODES}" \
        --seed "${seed}" \
        --seed_cycle "${SEED_CYCLE}" \
        --simTime "${SIM_TIME}" \
        --appStart "${APP_START}" \
        --periodMs "${PERIOD_MS}" \
        --max_steps "${EPISODE_STEPS}" \
        --ntsr "${EPISODE_STEPS}" \
        --observation_mode paper \
        --action_mode discrete \
        --consecutive_outage_steps "${CONSECUTIVE_OUTAGE_STEPS}" \
        --warmup_steps "${WARMUP_STEPS}" \
        --buffer_size "${DDQN_BUFFER_SIZE}" \
        --batch_size "${DDQN_BATCH_SIZE}" \
        --lr "${DDQN_LR}" \
        --gamma "${DDQN_GAMMA}" \
        --epsilon_start "${DDQN_EPS_START}" \
        --epsilon_min "${DDQN_EPS_MIN}" \
        --epsilon_decay "${DDQN_EPS_DECAY}" \
        --target_update "${DDQN_TARGET_UPDATE}" \
        --p_sta_static_fraction "${p_sta_fraction}" \
        --p_sta_weights "${P_STA_WEIGHTS}" \
        --reward_alpha "${REWARD_ALPHA}" \
        --reward_beta "${REWARD_BETA}" \
        --reward_gamma "${REWARD_GAMMA}" \
        --reward_mode "${reward_mode}" \
        --resource_efficiency_weight "${RESOURCE_EFFICIENCY_WEIGHT}" \
        --need_match_weight "${NEED_MATCH_WEIGHT}" \
        --waste_penalty_weight "${WASTE_PENALTY_WEIGHT}" \
        --under_allocation_penalty_weight "${UNDER_ALLOCATION_PENALTY_WEIGHT}" \
        --embb_soft_guard_penalty_weight "${EMBB_SOFT_GUARD_PENALTY_WEIGHT}" \
        --embb_soft_guard_ratio "${EMBB_SOFT_GUARD_RATIO}" \
        --action_smoothness_weight "${ACTION_SMOOTHNESS_WEIGHT}" \
        --resource_dynamic_need_weight "${RESOURCE_DYNAMIC_NEED_WEIGHT}" \
        --resource_waste_deadband "${RESOURCE_WASTE_DEADBAND}" \
        --compute_cost_per_hour_usd "${COMPUTE_COST_PER_HOUR_USD}" \
        --compute_avg_power_watts "${COMPUTE_AVG_POWER_WATTS}" \
        --compute_electricity_cost_usd_per_kwh "${COMPUTE_ELECTRICITY_COST_USD_PER_KWH}" \
        "${step_logging_args[@]}" \
        "${terminal_args[@]}" \
        --output "${OUTPUT_ROOT}/ddqn_${label}_${scenario}_seed${seed}"
}

run_sac() {
    local reward_mode="$1"
    local label="$2"
    local scenario="$3"
    local seed="$4"
    local p_sta_fraction="${P_STA_STATIC_FRACTION}"
    local terminal_args=()
    local step_logging_args=()
    if [[ "${reward_mode}" == "resource_efficient" ]]; then
        p_sta_fraction="${RESOURCE_EFFICIENT_P_STA_STATIC_FRACTION}"
    fi
    if [[ "${SAC_TERMINATE_ON_SLA_VIOLATION}" == "1" ]]; then
        terminal_args+=(--terminate-on-sla-violation)
    fi
    if [[ "${ENABLE_STEP_LOGGING}" != "1" ]]; then
        step_logging_args+=(--no-step-logging)
    fi

    echo "[SAC ${label}] scenario=${scenario} seed=${seed} reward=${reward_mode}"
    python3 examples/rslaq_train_sac.py \
        --scenario "${scenario}" \
        --episodes "${EPISODES}" \
        --seed "${seed}" \
        --seed_cycle "${SEED_CYCLE}" \
        --simTime "${SIM_TIME}" \
        --appStart "${APP_START}" \
        --periodMs "${PERIOD_MS}" \
        --max_steps "${EPISODE_STEPS}" \
        --observation_mode paper \
        --action_mode continuous \
        --consecutive_outage_steps "${CONSECUTIVE_OUTAGE_STEPS}" \
        --warmup_steps "${WARMUP_STEPS}" \
        --buffer_size "${SAC_BUFFER_SIZE}" \
        --batch_size "${SAC_BATCH_SIZE}" \
        --lr "${SAC_LR}" \
        --gamma "${SAC_GAMMA}" \
        --tau "${SAC_TAU}" \
        --alpha "${SAC_ALPHA}" \
        --p_sta_static_fraction "${p_sta_fraction}" \
        --p_sta_weights "${P_STA_WEIGHTS}" \
        --reward_alpha "${REWARD_ALPHA}" \
        --reward_beta "${REWARD_BETA}" \
        --reward_gamma "${REWARD_GAMMA}" \
        --reward_mode "${reward_mode}" \
        --resource_efficiency_weight "${RESOURCE_EFFICIENCY_WEIGHT}" \
        --need_match_weight "${NEED_MATCH_WEIGHT}" \
        --waste_penalty_weight "${WASTE_PENALTY_WEIGHT}" \
        --under_allocation_penalty_weight "${UNDER_ALLOCATION_PENALTY_WEIGHT}" \
        --embb_soft_guard_penalty_weight "${EMBB_SOFT_GUARD_PENALTY_WEIGHT}" \
        --embb_soft_guard_ratio "${EMBB_SOFT_GUARD_RATIO}" \
        --action_smoothness_weight "${ACTION_SMOOTHNESS_WEIGHT}" \
        --resource_dynamic_need_weight "${RESOURCE_DYNAMIC_NEED_WEIGHT}" \
        --resource_waste_deadband "${RESOURCE_WASTE_DEADBAND}" \
        --compute_cost_per_hour_usd "${COMPUTE_COST_PER_HOUR_USD}" \
        --compute_avg_power_watts "${COMPUTE_AVG_POWER_WATTS}" \
        --compute_electricity_cost_usd_per_kwh "${COMPUTE_ELECTRICITY_COST_USD_PER_KWH}" \
        "${step_logging_args[@]}" \
        "${terminal_args[@]}" \
        --output "${OUTPUT_ROOT}/sac_${label}_${scenario}_seed${seed}"
}

run_forecaster() {
    local cell_type="$1"
    local output_dir="$2"
    local source_root="${PREDICTIVE_FORECAST_SOURCE_ROOT}"

    local num_layers=1
    local dropout=0.0
    if [[ "${cell_type}" == "lstm" ]]; then
        num_layers=2
        dropout=0.2
    fi

    echo "[forecaster ${cell_type}] Training from baseline data: ${source_root} -> ${output_dir}"
    python3 examples/rslaq_train_forecaster.py \
        --cell_type "${cell_type}" \
        --source_root "${source_root}" \
        --source_format "${PREDICTIVE_FORECAST_SOURCE_FORMAT}" \
        --output "${output_dir}" \
        --sequence_len "${FORECAST_SEQUENCE_LEN}" \
        --forecast_horizon "${FORECAST_HORIZON}" \
        --hidden_dim "${FORECASTER_HIDDEN_DIM}" \
        --num_layers "${num_layers}" \
        --dropout "${dropout}" \
        --epochs "${FORECASTER_EPOCHS}" \
        --batch_size "${FORECASTER_BATCH_SIZE}" \
        --lr "${FORECASTER_LR}" \
        --compute_cost_per_hour_usd "${COMPUTE_COST_PER_HOUR_USD}" \
        --compute_avg_power_watts "${COMPUTE_AVG_POWER_WATTS}" \
        --compute_electricity_cost_usd_per_kwh "${COMPUTE_ELECTRICITY_COST_USD_PER_KWH}" \
        --limit_files "${FORECASTER_LIMIT_FILES}"
}

run_predictive_sac() {
    local scenario="$1"
    local seed="$2"
    local forecaster_ckpt="$3"
    local label="$4"
    local output_dir="${OUTPUT_ROOT}/predictive_sac_${scenario}_seed${seed}"
    local step_logging_args=()
    if [[ -n "${label}" ]]; then
        output_dir="${OUTPUT_ROOT}/predictive_sac_${label}_${scenario}_seed${seed}"
    fi
    if [[ "${ENABLE_STEP_LOGGING}" != "1" ]]; then
        step_logging_args+=(--no-step-logging)
    fi

    echo "[Predictive SAC ${label}] scenario=${scenario} seed=${seed} forecaster=${forecaster_ckpt}"
    python3 examples/rslaq_train_predictive_sac.py \
        --scenario "${scenario}" \
        --episodes "${EPISODES}" \
        --seed "${seed}" \
        --seed_cycle "${SEED_CYCLE}" \
        --simTime "${SIM_TIME}" \
        --appStart "${APP_START}" \
        --periodMs "${PERIOD_MS}" \
        --max_steps "${EPISODE_STEPS}" \
        --observation_mode paper \
        --consecutive_outage_steps "${CONSECUTIVE_OUTAGE_STEPS}" \
        --warmup_steps "${WARMUP_STEPS}" \
        --buffer_size "${SAC_BUFFER_SIZE}" \
        --batch_size "${SAC_BATCH_SIZE}" \
        --lr "${SAC_LR}" \
        --gamma "${SAC_GAMMA}" \
        --tau "${SAC_TAU}" \
        --alpha "${SAC_ALPHA}" \
        --p_sta_static_fraction "${PREDICTIVE_P_STA_FRACTION}" \
        --p_sta_weights "${P_STA_WEIGHTS}" \
        --reward_alpha "${REWARD_ALPHA}" \
        --reward_beta "${REWARD_BETA}" \
        --reward_gamma "${REWARD_GAMMA}" \
        --reward_mode "${PREDICTIVE_REWARD_MODE}" \
        --resource_efficiency_weight "${RESOURCE_EFFICIENCY_WEIGHT}" \
        --need_match_weight "${NEED_MATCH_WEIGHT}" \
        --waste_penalty_weight "${WASTE_PENALTY_WEIGHT}" \
        --under_allocation_penalty_weight "${UNDER_ALLOCATION_PENALTY_WEIGHT}" \
        --embb_soft_guard_penalty_weight "${EMBB_SOFT_GUARD_PENALTY_WEIGHT}" \
        --embb_soft_guard_ratio "${EMBB_SOFT_GUARD_RATIO}" \
        --action_smoothness_weight "${ACTION_SMOOTHNESS_WEIGHT}" \
        --resource_dynamic_need_weight "${RESOURCE_DYNAMIC_NEED_WEIGHT}" \
        --resource_waste_deadband "${RESOURCE_WASTE_DEADBAND}" \
        --risk_penalty "${RISK_PENALTY}" \
        --soft_penalty "${SOFT_PENALTY}" \
        --forecaster_checkpoint "${forecaster_ckpt}" \
        --sequence_len "${FORECAST_SEQUENCE_LEN}" \
        --compute_cost_per_hour_usd "${COMPUTE_COST_PER_HOUR_USD}" \
        --compute_avg_power_watts "${COMPUTE_AVG_POWER_WATTS}" \
        --compute_electricity_cost_usd_per_kwh "${COMPUTE_ELECTRICITY_COST_USD_PER_KWH}" \
        "${step_logging_args[@]}" \
        --output "${output_dir}"
}

DRL_FAILURES=0
DRL_RUNNING=0

run_drl_job() {
    if (( DRL_JOBS == 1 )); then
        "$@"
        return
    fi

    "$@" &
    DRL_RUNNING=$((DRL_RUNNING + 1))
    if (( DRL_RUNNING >= DRL_JOBS )); then
        if ! wait -n; then
            DRL_FAILURES=$((DRL_FAILURES + 1))
        fi
        DRL_RUNNING=$((DRL_RUNNING - 1))
    fi
}

wait_for_drl_jobs() {
    while (( DRL_RUNNING > 0 )); do
        if ! wait -n; then
            DRL_FAILURES=$((DRL_FAILURES + 1))
        fi
        DRL_RUNNING=$((DRL_RUNNING - 1))
    done

    if (( DRL_FAILURES > 0 )); then
        echo "DRL campaign failed: ${DRL_FAILURES} job(s) returned non-zero status" >&2
        exit 1
    fi
}

for scenario in "${SCENARIOS[@]}"; do
    for seed in "${SEEDS[@]}"; do
        if [[ "${RUN_DDQN}" == "1" ]]; then
            run_drl_job run_ddqn "paper" "paper" "${scenario}" "${seed}"
        fi
        if [[ "${RUN_RESOURCE_EFFICIENT_DDQN}" == "1" ]]; then
            run_drl_job run_ddqn "resource_efficient" "resource_efficient" "${scenario}" "${seed}"
        fi
        if [[ "${RUN_PAPER_SAC}" == "1" ]]; then
            run_drl_job run_sac "paper" "paper" "${scenario}" "${seed}"
        fi
        if [[ "${RUN_RESOURCE_EFFICIENT_SAC}" == "1" ]]; then
            run_drl_job run_sac "resource_efficient" "resource_efficient" "${scenario}" "${seed}"
        fi
    done
done

wait_for_drl_jobs

FORECASTER_GRU_CHECKPOINT="${OUTPUT_ROOT}/forecaster_gru/forecaster_best.pt"
FORECASTER_LSTM_CHECKPOINT="${OUTPUT_ROOT}/forecaster_lstm/forecaster_best.pt"

if [[ "${RUN_FORECASTER}" == "1" ]]; then
    if [[ "${RUN_FORECASTER_GRU}" == "1" ]]; then
        run_forecaster "gru" "${OUTPUT_ROOT}/forecaster_gru"
    fi
    if [[ "${RUN_FORECASTER_LSTM}" == "1" ]]; then
        run_forecaster "lstm" "${OUTPUT_ROOT}/forecaster_lstm"
    fi
else
    echo "[forecaster] Skipping forecaster training because RUN_FORECASTER=${RUN_FORECASTER}"
    if [[ -n "${FORECASTER_CHECKPOINT}" && -f "${FORECASTER_CHECKPOINT}" ]]; then
        FORECASTER_GRU_CHECKPOINT="${FORECASTER_CHECKPOINT}"
        FORECASTER_LSTM_CHECKPOINT="${FORECASTER_CHECKPOINT}"
    fi
fi

if [[ "${RUN_FORECASTER_COMPARISON}" == "1" && "${RUN_FORECASTER_GRU}" == "1" && "${RUN_FORECASTER_LSTM}" == "1" ]]; then
    echo "[forecaster comparison] Running offline GRU vs LSTM comparison"
    python3 examples/compare_forecasters.py \
        --gru_checkpoint "${FORECASTER_GRU_CHECKPOINT}" \
        --lstm_checkpoint "${FORECASTER_LSTM_CHECKPOINT}" \
        --source_root "${PREDICTIVE_FORECAST_SOURCE_ROOT}" \
        --source_format "${PREDICTIVE_FORECAST_SOURCE_FORMAT}" \
        --sequence_len "${FORECAST_SEQUENCE_LEN}" \
        --forecast_horizon "${FORECAST_HORIZON}" \
        --output "${OUTPUT_ROOT}/forecaster_comparison"

    python3 examples/plot_forecaster_comparison.py \
        --comparison_json "${OUTPUT_ROOT}/forecaster_comparison/forecaster_comparison.json" \
        --gru_dir "${OUTPUT_ROOT}/forecaster_gru" \
        --lstm_dir "${OUTPUT_ROOT}/forecaster_lstm" \
        --output "${OUTPUT_ROOT}/forecaster_article_figures"
fi

if [[ "${RUN_PREDICTIVE_SAC}" == "1" ]]; then
    for scenario in "${SCENARIOS[@]}"; do
        for seed in "${SEEDS[@]}"; do
            if [[ "${RUN_PREDICTIVE_SAC_GRU}" == "1" ]]; then
                run_drl_job run_predictive_sac "${scenario}" "${seed}" "${FORECASTER_GRU_CHECKPOINT}" "gru"
            fi
            if [[ "${RUN_PREDICTIVE_SAC_LSTM}" == "1" ]]; then
                run_drl_job run_predictive_sac "${scenario}" "${seed}" "${FORECASTER_LSTM_CHECKPOINT}" "lstm"
            fi
            if [[ "${RUN_PREDICTIVE_SAC_GRU}" != "1" && "${RUN_PREDICTIVE_SAC_LSTM}" != "1" ]]; then
                # Default legacy behavior: single predictive_sac without gru/lstm label
                run_drl_job run_predictive_sac "${scenario}" "${seed}" "${FORECASTER_GRU_CHECKPOINT}" ""
            fi
        done
    done
    wait_for_drl_jobs
fi

write_drl_comparison() {
    python3 - "${OUTPUT_ROOT}" <<'PY'
import csv
import io
import json
import re
import sys
from collections import defaultdict
from pathlib import Path
from statistics import mean

root = Path(sys.argv[1])

LINE_SPECS = [
    {
        "line": "ddqn_paper",
        "algo": "ddqn",
        "reward_mode": "paper",
        "pattern": re.compile(r"ddqn_paper_(.*)_seed(\d+)$"),
        "training_log": "ddqn_training_log.csv",
        "summary_file": "ddqn_summary.json",
    },
    {
        "line": "ddqn_resource_efficient",
        "algo": "ddqn",
        "reward_mode": "resource_efficient",
        "pattern": re.compile(r"ddqn_resource_efficient_(.*)_seed(\d+)$"),
        "training_log": "ddqn_training_log.csv",
        "summary_file": "ddqn_summary.json",
    },
    {
        "line": "sac_paper",
        "algo": "sac",
        "reward_mode": "paper",
        "pattern": re.compile(r"sac_paper_(.*)_seed(\d+)$"),
        "training_log": "sac_training_log.csv",
        "summary_file": "sac_summary.json",
    },
    {
        "line": "sac_resource_efficient",
        "algo": "sac",
        "reward_mode": "resource_efficient",
        "pattern": re.compile(r"sac_resource_efficient_(.*)_seed(\d+)$"),
        "training_log": "sac_training_log.csv",
        "summary_file": "sac_summary.json",
    },
    {
        "line": "predictive_sac",
        "algo": "predictive_sac",
        "reward_mode": "resource_efficient",
        "pattern": re.compile(r"predictive_sac_(.*)_seed(\d+)$"),
        "training_log": "sac_training_log.csv",
        "summary_file": "sac_summary.json",
    },
    {
        "line": "predictive_sac_gru",
        "algo": "predictive_sac",
        "reward_mode": "resource_efficient",
        "pattern": re.compile(r"predictive_sac_gru_(.*)_seed(\d+)$"),
        "training_log": "sac_training_log.csv",
        "summary_file": "sac_summary.json",
    },
    {
        "line": "predictive_sac_lstm",
        "algo": "predictive_sac",
        "reward_mode": "resource_efficient",
        "pattern": re.compile(r"predictive_sac_lstm_(.*)_seed(\d+)$"),
        "training_log": "sac_training_log.csv",
        "summary_file": "sac_summary.json",
    },
]


def safe_text(path: Path) -> str:
    return path.read_bytes().replace(b"\x00", b"").decode("utf-8", errors="replace")


def read_csv(path: Path):
    if not path.exists():
        return []
    return list(csv.DictReader(io.StringIO(safe_text(path))))


def read_json(path: Path):
    if not path.exists():
        return {}
    try:
        return json.loads(safe_text(path))
    except json.JSONDecodeError:
        return {}


def to_float(value, default=0.0):
    try:
        if value in (None, "", "NA"):
            return default
        return float(value)
    except (TypeError, ValueError):
        return default


def to_int(value, default=0):
    try:
        return int(float(str(value).strip()))
    except (TypeError, ValueError):
        return default


def avg(values):
    values = [value for value in values if value is not None]
    return mean(values) if values else 0.0


def tail_training_summary(run_dir: Path, training_log: str):
    rows = read_csv(run_dir / training_log)
    rows = [row for row in rows if to_int(row.get("episode"), -1) > 0]
    rows.sort(key=lambda row: to_int(row.get("episode")))
    if not rows:
        return {"episodes": 0}
    tail = rows[-10:]
    return {
        "episodes": len(rows),
        "tail_reward": avg(to_float(row.get("total_reward")) for row in tail),
        "tail_outages": avg(to_float(row.get("outage_count")) for row in tail),
        "tail_soft": avg(to_float(row.get("soft_count")) for row in tail),
        "final_avg_reward": to_float(rows[-1].get("avg_reward")),
        "max_episode": to_int(rows[-1].get("episode")),
    }


def compute_summary(run_dir: Path, summary_file: str):
    compute = read_json(run_dir / summary_file).get("compute", {})
    training = compute.get("training", {})
    xapp = compute.get("xapp_runtime", {})
    cost = compute.get("cost_estimate", {})
    return {
        "compute_wall_time_s": to_float(training.get("wall_time_s")),
        "compute_cpu_time_s": to_float(training.get("cpu_time_s")),
        "compute_child_cpu_time_s": to_float(training.get("child_cpu_time_s")),
        "compute_peak_rss_mb": to_float(training.get("peak_rss_mb")),
        "compute_child_peak_rss_mb": to_float(training.get("child_peak_rss_mb")),
        "compute_steps_per_second": to_float(training.get("steps_per_second")),
        "xapp_decision_count": to_int(xapp.get("decision_count")),
        "xapp_inference_ms_mean": to_float(xapp.get("inference_ms_mean")),
        "xapp_inference_ms_p50": to_float(xapp.get("inference_ms_p50")),
        "xapp_inference_ms_p95": to_float(xapp.get("inference_ms_p95")),
        "xapp_inference_ms_max": to_float(xapp.get("inference_ms_max")),
        "xapp_deadline_usage_pct": to_float(xapp.get("deadline_usage_pct")),
        "compute_cloud_cost_usd": to_float(cost.get("cloud_cost_usd")),
        "compute_cost_per_1000_steps_usd": to_float(cost.get("cost_per_1000_steps_usd")),
        "compute_energy_kwh": to_float(cost.get("energy_kwh")),
        "compute_energy_cost_usd": to_float(cost.get("energy_cost_usd")),
    }


def step_summary(run_dir: Path, max_episode: int):
    lower_episode = max(max_episode - 10, 0) if max_episode > 0 else 0
    grouped = defaultdict(list)
    for path in run_dir.glob("*/step_metrics.csv"):
        for row in read_csv(path):
            episode = to_int(row.get("episode"), -1)
            if episode <= lower_episode:
                continue
            key = (row.get("sim_id"), row.get("episode"), row.get("step"))
            grouped[key].append(row)

    step_count = len(grouped)
    totals = defaultdict(float)
    slice_totals = defaultdict(lambda: defaultdict(float))
    slice_counts = defaultdict(int)

    for rows in grouped.values():
        first = rows[0]
        has_outage = any(row.get("outage_flag") == "True" for row in rows)
        has_soft = any(row.get("soft_flag") == "True" for row in rows)
        totals["outage_rate"] += float(has_outage)
        totals["soft_rate"] += float(has_soft)
        totals["violation_rate"] += float(has_outage or has_soft)
        for name in [
            "reward", "resource_efficiency", "need_allocation_match",
            "over_allocation", "under_allocation", "action_smoothness_penalty",
            "resource_efficient_shaping", "action_embb", "action_urllc", "action_mtc",
        ]:
            totals[name] += to_float(first.get(name))

        for row in rows:
            sid = to_int(row.get("slice_id"), -1)
            if sid not in (0, 1, 2):
                continue
            prefix = ["embb", "urllc", "mtc"][sid]
            slice_counts[prefix] += 1
            for metric, column in [
                ("thr", "throughput_mbps"),
                ("plr", "plr_pct"),
                ("buffer", "bufferBytes_mean"),
                ("lost", "dLostPackets"),
                ("rsh", "resourceSharePct"),
            ]:
                slice_totals[prefix][metric] += to_float(row.get(column))

    denom = max(step_count, 1)
    result = {"step_count": step_count}
    for name, total in totals.items():
        result[name] = total / denom
    result["sla_reliability"] = 1.0 - result.get("violation_rate", 0.0)

    for prefix in ["embb", "urllc", "mtc"]:
        denom_slice = max(slice_counts[prefix], 1)
        for metric, total in slice_totals[prefix].items():
            result[f"{prefix}_{metric}"] = total / denom_slice
    rsh_values = [result.get("embb_rsh", 0.0), result.get("urllc_rsh", 0.0), result.get("mtc_rsh", 0.0)]
    rsh_sq_sum = sum(value * value for value in rsh_values)
    result["resource_fairness"] = (sum(rsh_values) ** 2) / (3.0 * rsh_sq_sum) if rsh_sq_sum > 0.0 else 0.0
    return result


def collect_runs():
    rows = []
    for run_dir in root.iterdir():
        if not run_dir.is_dir():
            continue
        for spec in LINE_SPECS:
            match = spec["pattern"].match(run_dir.name)
            if not match:
                continue
            scenario, seed = match.group(1), int(match.group(2))
            training = tail_training_summary(run_dir, spec["training_log"])
            step = step_summary(run_dir, training.get("max_episode", 0))
            compute = compute_summary(run_dir, spec["summary_file"])
            row = {
                "line": spec["line"],
                "algo": spec["algo"],
                "reward_mode": spec["reward_mode"],
                "scenario": scenario,
                "seed": seed,
                "run_dir": str(run_dir),
            }
            row.update(training)
            row.update(step)
            row.update(compute)
            rows.append(row)
            break
    return rows


def aggregate(rows):
    groups = defaultdict(list)
    for row in rows:
        groups[(row["line"], row["algo"], row["reward_mode"], row["scenario"])].append(row)

    numeric_keys = sorted(
        key
        for key in {key for row in rows for key in row.keys()}
        if key not in {"line", "algo", "reward_mode", "scenario", "seed", "run_dir"}
    )
    summary_rows = []
    for key, items in sorted(groups.items()):
        row = {
            "line": key[0],
            "algo": key[1],
            "reward_mode": key[2],
            "scenario": key[3],
            "runs": len(items),
        }
        for metric in numeric_keys:
            row[metric] = avg(to_float(item.get(metric)) for item in items)
        summary_rows.append(row)
    return summary_rows


def norm_map(rows, metric, higher_is_better=True):
    values = [to_float(row.get(metric)) for row in rows]
    lo = min(values) if values else 0.0
    hi = max(values) if values else 0.0
    if hi == lo:
        return {id(row): 0.5 for row in rows}
    scores = {}
    for row, value in zip(rows, values):
        scaled = (value - lo) / (hi - lo)
        scores[id(row)] = scaled if higher_is_better else 1.0 - scaled
    return scores


def build_rankings(summary_rows):
    ranked = []
    by_scenario = defaultdict(list)
    for row in summary_rows:
        by_scenario[row["scenario"]].append(row)

    for scenario, rows in sorted(by_scenario.items()):
        maps = {
            "sla_reliability": norm_map(rows, "sla_reliability", True),
            "outage_rate": norm_map(rows, "outage_rate", False),
            "soft_rate": norm_map(rows, "soft_rate", False),
            "embb_thr": norm_map(rows, "embb_thr", True),
            "urllc_plr": norm_map(rows, "urllc_plr", False),
            "mtc_lost": norm_map(rows, "mtc_lost", False),
            "resource_efficiency": norm_map(rows, "resource_efficiency", True),
            "need_allocation_match": norm_map(rows, "need_allocation_match", True),
            "over_allocation": norm_map(rows, "over_allocation", False),
            "under_allocation": norm_map(rows, "under_allocation", False),
            "resource_fairness": norm_map(rows, "resource_fairness", True),
            "action_smoothness_penalty": norm_map(rows, "action_smoothness_penalty", False),
        }
        scored = []
        for row in rows:
            key = id(row)
            sla_score = (
                0.50 * maps["sla_reliability"][key]
                + 0.25 * maps["outage_rate"][key]
                + 0.25 * maps["soft_rate"][key]
            )
            service_score = (
                0.40 * maps["embb_thr"][key]
                + 0.30 * maps["urllc_plr"][key]
                + 0.30 * maps["mtc_lost"][key]
            )
            resource_score = (
                0.40 * maps["resource_efficiency"][key]
                + 0.25 * maps["need_allocation_match"][key]
                + 0.175 * maps["over_allocation"][key]
                + 0.175 * maps["under_allocation"][key]
            )
            fairness_score = maps["resource_fairness"][key]
            stability_score = maps["action_smoothness_penalty"][key]
            score = (
                0.35 * sla_score
                + 0.20 * service_score
                + 0.25 * resource_score
                + 0.10 * fairness_score
                + 0.10 * stability_score
            )
            out = dict(row)
            out.update({
                "score": score,
                "sla_score": sla_score,
                "service_score": service_score,
                "resource_score": resource_score,
                "fairness_score": fairness_score,
                "stability_score": stability_score,
            })
            scored.append(out)

        scored.sort(key=lambda row: row["score"], reverse=True)
        for rank, row in enumerate(scored, start=1):
            row["rank"] = rank
            ranked.append(row)

    overall = []
    by_line = defaultdict(list)
    for row in ranked:
        by_line[row["line"]].append(row)
    for line, rows in sorted(by_line.items()):
        out = {
            "line": line,
            "algo": rows[0]["algo"],
            "reward_mode": rows[0]["reward_mode"],
            "scenarios": len(rows),
            "mean_score": avg(row["score"] for row in rows),
            "mean_rank": avg(row["rank"] for row in rows),
            "rank_1_count": sum(1 for row in rows if row["rank"] == 1),
        }
        overall.append(out)
    overall.sort(key=lambda row: (-row["mean_score"], row["mean_rank"]))
    for rank, row in enumerate(overall, start=1):
        row["overall_rank"] = rank
    return ranked, overall

def write_csv(path: Path, rows):
    if not rows:
        return
    keys = sorted({key for row in rows for key in row.keys()})
    with path.open("w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=keys)
        writer.writeheader()
        writer.writerows(rows)

run_rows = collect_runs()
summary = aggregate(run_rows)
ranking, overall = build_rankings(summary)

write_csv(root / "drl_comparison_by_run.csv", run_rows)
write_csv(root / "drl_comparison_summary.csv", summary)
write_csv(root / "drl_ranking.csv", ranking)
write_csv(root / "drl_overall_ranking.csv", overall)
with (root / "drl_comparison.json").open("w") as f:
    json.dump({"runs": run_rows, "summary": summary, "ranking": ranking, "overall": overall}, f, indent=2)

print(f"[compare] Unified DRL comparison: {len(run_rows)} run(s), {len(summary)} scenario line(s)")
if ranking:
    print(f"[compare] Wrote {root / 'drl_ranking.csv'}")
else:
    print("[compare] No DRL run directories found")
PY
}

if [[ "${RUN_DRL_COMPARISON}" == "1" ]]; then
    write_drl_comparison
fi

cat > "${OUTPUT_ROOT}/campaign_config.json" <<EOF
{
  "experiment_line": "${EXPERIMENT_LINE}",
  "run_tag": "${RUN_TAG}",
  "scenarios": "${SCENARIOS[*]}",
  "seeds": "${SEEDS[*]}",
  "episodes": ${EPISODES},
  "episode_steps": ${EPISODE_STEPS},
  "interaction_budget": $((EPISODES * EPISODE_STEPS)),
  "sim_time": ${SIM_TIME},
  "app_start": ${APP_START},
  "period_ms": ${PERIOD_MS},
  "run_baselines": ${RUN_BASELINES},
  "baseline_modes": "${BASELINE_MODES}",
  "run_ddqn": ${RUN_DDQN},
  "run_resource_efficient_ddqn": ${RUN_RESOURCE_EFFICIENT_DDQN},
  "ddqn_terminate_on_sla_violation": ${DDQN_TERMINATE_ON_SLA_VIOLATION},
  "sac_terminate_on_sla_violation": ${SAC_TERMINATE_ON_SLA_VIOLATION},
  "run_paper_sac": ${RUN_PAPER_SAC},
  "run_resource_efficient_sac": ${RUN_RESOURCE_EFFICIENT_SAC},
  "run_forecaster": ${RUN_FORECASTER},
  "run_forecaster_gru": ${RUN_FORECASTER_GRU},
  "run_forecaster_lstm": ${RUN_FORECASTER_LSTM},
  "run_forecaster_comparison": ${RUN_FORECASTER_COMPARISON},
  "run_predictive_sac": ${RUN_PREDICTIVE_SAC},
  "run_predictive_sac_gru": ${RUN_PREDICTIVE_SAC_GRU},
  "run_predictive_sac_lstm": ${RUN_PREDICTIVE_SAC_LSTM},
  "predictive_sac": {
    "reward_mode": "${PREDICTIVE_REWARD_MODE}",
    "p_sta_static_fraction": ${PREDICTIVE_P_STA_FRACTION},
    "risk_penalty": ${RISK_PENALTY},
    "soft_penalty": ${SOFT_PENALTY},
    "forecast_sequence_len": ${FORECAST_SEQUENCE_LEN},
    "forecast_horizon": ${FORECAST_HORIZON},
    "forecaster_epochs": ${FORECASTER_EPOCHS},
    "forecaster_batch_size": ${FORECASTER_BATCH_SIZE},
    "forecaster_lr": ${FORECASTER_LR},
    "forecaster_hidden_dim": ${FORECASTER_HIDDEN_DIM},
    "forecaster_limit_files": ${FORECASTER_LIMIT_FILES},
    "baseline_root": "${PREDICTIVE_BASELINE_ROOT}",
    "forecast_source_root": "${PREDICTIVE_FORECAST_SOURCE_ROOT}",
    "forecast_source_format": "${PREDICTIVE_FORECAST_SOURCE_FORMAT}"
  },
  "build_ns3": ${BUILD_NS3},
  "drl_jobs": ${DRL_JOBS},
  "enable_step_logging": ${ENABLE_STEP_LOGGING},
  "run_drl_comparison": ${RUN_DRL_COMPARISON},
  "p_sta_static_fraction": ${P_STA_STATIC_FRACTION},
  "resource_efficient_p_sta_static_fraction": ${RESOURCE_EFFICIENT_P_STA_STATIC_FRACTION},
  "p_sta_weights": "${P_STA_WEIGHTS}",
  "reward_weights": "${REWARD_ALPHA},${REWARD_BETA},${REWARD_GAMMA}",
  "resource_efficient_reward": {
    "resource_efficiency_weight": ${RESOURCE_EFFICIENCY_WEIGHT},
    "need_match_weight": ${NEED_MATCH_WEIGHT},
    "waste_penalty_weight": ${WASTE_PENALTY_WEIGHT},
    "under_allocation_penalty_weight": ${UNDER_ALLOCATION_PENALTY_WEIGHT},
    "embb_soft_guard_penalty_weight": ${EMBB_SOFT_GUARD_PENALTY_WEIGHT},
    "embb_soft_guard_ratio": ${EMBB_SOFT_GUARD_RATIO},
    "action_smoothness_weight": ${ACTION_SMOOTHNESS_WEIGHT},
    "resource_dynamic_need_weight": ${RESOURCE_DYNAMIC_NEED_WEIGHT},
    "resource_waste_deadband": ${RESOURCE_WASTE_DEADBAND}
  },
  "compute_cost": {
    "cost_per_hour_usd": ${COMPUTE_COST_PER_HOUR_USD},
    "avg_power_watts": ${COMPUTE_AVG_POWER_WATTS},
    "electricity_cost_usd_per_kwh": ${COMPUTE_ELECTRICITY_COST_USD_PER_KWH}
  }
}
EOF

echo "Controlled campaign complete: ${OUTPUT_ROOT}"
